#if !defined DIALOG_STYLES
	#define DIALOG_STYLES
	#define DIALOG_STYLE_MSGBOX 0
	#define DIALOG_STYLE_INPUT 1
	#define DIALOG_STYLE_LIST 2
	#define DIALOG_STYLE_PASSWORD 3
	#define DIALOG_STYLE_TABLIST 4
	#define DIALOG_STYLE_TABLIST_HEADERS 5
#endif